<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['browse_record']=array (
  'id' => '7',
  'name' => 'browse_record',
  'description' => '浏览记录',
  'perpage' => '50',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    48 => 
    array (
      'id' => '48',
      'name' => 'cms_id',
      'description' => '文章ID',
      'model' => '7',
      'type' => 'int',
      'length' => '8',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    49 => 
    array (
      'id' => '49',
      'name' => 'cms_title',
      'description' => '文章标题',
      'model' => '7',
      'type' => 'input',
      'length' => '200',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    50 => 
    array (
      'id' => '50',
      'name' => 'count',
      'description' => '点击数量',
      'model' => '7',
      'type' => 'int',
      'length' => '8',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    51 => 
    array (
      'id' => '51',
      'name' => 'menu_name',
      'description' => '栏目',
      'model' => '7',
      'type' => 'input',
      'length' => '200',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '48',
    1 => '49',
    2 => '50',
    3 => '51',
  ),
  'searchable' => 
  array (
    0 => '48',
    1 => '49',
    2 => '50',
    3 => '51',
  ),
);