<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['cms']=array (
  'id' => '1',
  'name' => 'cms',
  'description' => '文章管理',
  'perpage' => '20',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    1 => 
    array (
      'id' => '1',
      'name' => 'title',
      'description' => '标题',
      'model' => '1',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    4 => 
    array (
      'id' => '4',
      'name' => 'menu_name',
      'description' => '栏目名称',
      'model' => '1',
      'type' => 'select_from_model',
      'length' => '100',
      'values' => 'menu|menu_name',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    5 => 
    array (
      'id' => '5',
      'name' => 'detail_info',
      'description' => '详细信息',
      'model' => '1',
      'type' => 'wysiwyg_basic',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    27 => 
    array (
      'id' => '27',
      'name' => 'display_flg',
      'description' => '是否投稿',
      'model' => '1',
      'type' => 'checkbox',
      'length' => '8',
      'values' => 
      array (
        1 => '投稿',
        0 => '不投稿',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    28 => 
    array (
      'id' => '28',
      'name' => 'approve_flg',
      'description' => '审核标志',
      'model' => '1',
      'type' => 'int',
      'length' => '8',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '0',
    ),
    34 => 
    array (
      'id' => '34',
      'name' => 'display_top_flg',
      'description' => '置顶标志',
      'model' => '1',
      'type' => 'checkbox',
      'length' => '8',
      'values' => 
      array (
        1 => '置顶',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '5',
      'editable' => '0',
    ),
    43 => 
    array (
      'id' => '43',
      'name' => 'smallimage',
      'description' => '插图',
      'model' => '1',
      'type' => 'file',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '5',
      'editable' => '1',
    ),
    52 => 
    array (
      'id' => '52',
      'name' => 'editor',
      'description' => '责任编辑',
      'model' => '1',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    44 => 
    array (
      'id' => '44',
      'name' => 'imgSendFlg',
      'description' => '插图推送到首页',
      'model' => '1',
      'type' => 'select',
      'length' => '100',
      'values' => 
      array (
        1 => '推送',
        0 => '不推送',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    47 => 
    array (
      'id' => '47',
      'name' => 'writer',
      'description' => '作者',
      'model' => '1',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    46 => 
    array (
      'id' => '46',
      'name' => 'cms_from',
      'description' => '文章来源',
      'model' => '1',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1',
    1 => '4',
    2 => '5',
    3 => '27',
    4 => '28',
    5 => '52',
    6 => '44',
    7 => '47',
    8 => '46',
  ),
  'searchable' => 
  array (
    0 => '1',
    1 => '4',
    2 => '5',
    3 => '27',
    4 => '34',
    5 => '52',
    6 => '44',
    7 => '47',
    8 => '46',
  ),
);