<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['companies']=array (
  'id' => '1',
  'name' => 'companies',
  'description' => '公司管理',
  'perpage' => '5',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    1 => 
    array (
      'id' => '1',
      'name' => 'classid',
      'description' => '公司所属分类',
      'model' => '1',
      'type' => 'select_from_model',
      'length' => '8',
      'values' => 'companies_class|title',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    2 => 
    array (
      'id' => '2',
      'name' => 'title',
      'description' => '公司名称',
      'model' => '1',
      'type' => 'input',
      'length' => '150',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    52 => 
    array (
      'id' => '52',
      'name' => 'cover',
      'description' => '公司logo',
      'model' => '1',
      'type' => 'file',
      'length' => '255',
      'values' => 'jpg|png|jpeg|bmp',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    50 => 
    array (
      'id' => '50',
      'name' => 'intro',
      'description' => '公司简介',
      'model' => '1',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    51 => 
    array (
      'id' => '51',
      'name' => 'info',
      'description' => '公司详细介绍',
      'model' => '1',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '5',
      'editable' => '1',
    ),
    5 => 
    array (
      'id' => '5',
      'name' => 'sort',
      'description' => '排序',
      'model' => '1',
      'type' => 'int',
      'length' => '4',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1',
    1 => '2',
    2 => '52',
    3 => '50',
    4 => '5',
  ),
  'searchable' => 
  array (
    0 => '2',
  ),
);