<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['news']=array (
  'id' => '5',
  'name' => 'news',
  'description' => '新闻管理',
  'perpage' => '5',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    49 => 
    array (
      'id' => '49',
      'name' => 'classid',
      'description' => '新闻所属分类',
      'model' => '5',
      'type' => 'radio_from_model',
      'length' => '8',
      'values' => 'news_class|title',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    34 => 
    array (
      'id' => '34',
      'name' => 'subclassid',
      'description' => '分类下的栏目分类',
      'model' => '5',
      'type' => 'select',
      'length' => '8',
      'values' => 
      array (
      ),
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '2',
      'editable' => '1',
    ),
    35 => 
    array (
      'id' => '35',
      'name' => 'title',
      'description' => '新闻标题',
      'model' => '5',
      'type' => 'input',
      'length' => '150',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    37 => 
    array (
      'id' => '37',
      'name' => 'cover',
      'description' => '新闻封面图',
      'model' => '5',
      'type' => 'file',
      'length' => '255',
      'values' => 'jpg|png|jpeg|bmp',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    38 => 
    array (
      'id' => '38',
      'name' => 'intro',
      'description' => '新闻简介',
      'model' => '5',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    39 => 
    array (
      'id' => '39',
      'name' => 'info',
      'description' => '新闻详细内容',
      'model' => '5',
      'type' => 'wysiwyg_basic',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '6',
      'editable' => '1',
    ),
    42 => 
    array (
      'id' => '42',
      'name' => 'sort',
      'description' => '排序',
      'model' => '5',
      'type' => 'int',
      'length' => '8',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    36 => 
    array (
      'id' => '36',
      'name' => 'recommend1',
      'description' => '相关新闻推荐1',
      'model' => '5',
      'type' => 'content',
      'length' => '10',
      'values' => 'news|title',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '8',
      'editable' => '1',
    ),
    48 => 
    array (
      'id' => '48',
      'name' => 'recommend2',
      'description' => '相关新闻推荐2',
      'model' => '5',
      'type' => 'content',
      'length' => '8',
      'values' => 'news|title',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '9',
      'editable' => '1',
    ),
    57 => 
    array (
      'id' => '57',
      'name' => 'projects_id',
      'description' => '所属项目名称',
      'model' => '5',
      'type' => 'content',
      'length' => '8',
      'values' => 'projects|title',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '10',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '49',
    1 => '35',
    2 => '37',
    3 => '38',
    4 => '42',
  ),
  'searchable' => 
  array (
  ),
);