<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['person_product']=array (
  'id' => '2',
  'name' => 'person_product',
  'description' => '作品发布',
  'perpage' => '20',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    10 => 
    array (
      'id' => '10',
      'name' => 'product_title',
      'description' => '作品标题',
      'model' => '2',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    6 => 
    array (
      'id' => '6',
      'name' => 'kuan_shi',
      'description' => '款识',
      'model' => '2',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    13 => 
    array (
      'id' => '13',
      'name' => 'qian_yin',
      'description' => '钤印',
      'model' => '2',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    14 => 
    array (
      'id' => '14',
      'name' => 'size',
      'description' => '尺寸',
      'model' => '2',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    15 => 
    array (
      'id' => '15',
      'name' => 'zuo_zhe',
      'description' => '作者',
      'model' => '2',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    16 => 
    array (
      'id' => '16',
      'name' => 'value',
      'description' => '估值',
      'model' => '2',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    12 => 
    array (
      'id' => '12',
      'name' => 'product_year',
      'description' => '作品年份',
      'model' => '2',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    11 => 
    array (
      'id' => '11',
      'name' => 'product_type',
      'description' => '作品分类',
      'model' => '2',
      'type' => 'select_from_model',
      'length' => '100',
      'values' => 'product_type|type_name',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    33 => 
    array (
      'id' => '33',
      'name' => 'display_top_flg',
      'description' => '置顶标志',
      'model' => '2',
      'type' => 'checkbox',
      'length' => '8',
      'values' => 
      array (
        1 => '置顶',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '8',
      'editable' => '0',
    ),
    8 => 
    array (
      'id' => '8',
      'name' => 'product_img',
      'description' => '作品图片',
      'model' => '2',
      'type' => 'file',
      'length' => '1000',
      'values' => 'jpg|png|jpeg|bmp',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '9',
      'editable' => '1',
    ),
    9 => 
    array (
      'id' => '9',
      'name' => 'product_mark',
      'description' => '关键字',
      'model' => '2',
      'type' => 'select_from_model',
      'length' => '100',
      'values' => 'product_mark|mark_name',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    7 => 
    array (
      'id' => '7',
      'name' => 'product_detail_info',
      'description' => '详细信息',
      'model' => '2',
      'type' => 'wysiwyg_basic',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    30 => 
    array (
      'id' => '30',
      'name' => 'tui_guang',
      'description' => '推广标志',
      'model' => '2',
      'type' => 'int',
      'length' => '8',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '11',
      'editable' => '0',
    ),
  ),
  'listable' => 
  array (
    0 => '10',
    1 => '6',
    2 => '13',
    3 => '14',
    4 => '15',
    5 => '16',
    6 => '12',
    7 => '11',
    8 => '9',
    9 => '7',
    10 => '30',
  ),
  'searchable' => 
  array (
    0 => '10',
    1 => '6',
    2 => '13',
    3 => '14',
    4 => '15',
    5 => '16',
    6 => '12',
    7 => '11',
    8 => '33',
    9 => '9',
    10 => '7',
  ),
);