<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['person_detail_info']=array (
  'id' => '3',
  'name' => 'person_detail_info',
  'description' => '会员详细信息',
  'perpage' => '1',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    21 => 
    array (
      'id' => '21',
      'name' => 'person_name',
      'description' => '姓名',
      'model' => '3',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    17 => 
    array (
      'id' => '17',
      'name' => 'bie_shu',
      'description' => '别署',
      'model' => '3',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    18 => 
    array (
      'id' => '18',
      'name' => 'hao_long',
      'description' => '号龙',
      'model' => '3',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    20 => 
    array (
      'id' => '20',
      'name' => 'person_img',
      'description' => '头像',
      'model' => '3',
      'type' => 'file',
      'length' => '1000',
      'values' => 'jpg|png|jpeg|bmp',
      'width' => '100',
      'height' => '100',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    22 => 
    array (
      'id' => '22',
      'name' => 'run_ge',
      'description' => '润格',
      'model' => '3',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    23 => 
    array (
      'id' => '23',
      'name' => 'sex',
      'description' => '性别',
      'model' => '3',
      'type' => 'select',
      'length' => '100',
      'values' => 
      array (
        1 => '男',
        2 => '女',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    24 => 
    array (
      'id' => '24',
      'name' => 'xue_ming',
      'description' => '学名',
      'model' => '3',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    19 => 
    array (
      'id' => '19',
      'name' => 'person_detail_info',
      'description' => '个人详细信息',
      'model' => '3',
      'type' => 'input',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '21',
    1 => '17',
    2 => '18',
    3 => '20',
    4 => '22',
    5 => '23',
    6 => '24',
    7 => '19',
  ),
  'searchable' => 
  array (
    0 => '21',
    1 => '17',
    2 => '18',
    3 => '20',
    4 => '22',
    5 => '23',
    6 => '24',
    7 => '19',
  ),
);