<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['products']=array (
  'id' => '2',
  'name' => 'products',
  'description' => '产品管理',
  'perpage' => '5',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    60 => 
    array (
      'id' => '60',
      'name' => 'classid',
      'description' => '所属分类',
      'model' => '2',
      'type' => 'radio_from_model',
      'length' => '8',
      'values' => 'products_class|title',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '0',
      'editable' => '1',
    ),
    7 => 
    array (
      'id' => '7',
      'name' => 'title',
      'description' => '产品名称',
      'model' => '2',
      'type' => 'input',
      'length' => '150',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    8 => 
    array (
      'id' => '8',
      'name' => 'adv',
      'description' => '广告位图片',
      'model' => '2',
      'type' => 'file',
      'length' => '255',
      'values' => 'jpg|png|jpeg|bmp',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '3',
      'editable' => '1',
    ),
    9 => 
    array (
      'id' => '9',
      'name' => 'cover',
      'description' => '产品封面图',
      'model' => '2',
      'type' => 'file',
      'length' => '255',
      'values' => 'jpg|png|jpeg|bmp',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    10 => 
    array (
      'id' => '10',
      'name' => 'intro',
      'description' => '产品简介',
      'model' => '2',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    11 => 
    array (
      'id' => '11',
      'name' => 'info',
      'description' => '产品详细介绍',
      'model' => '2',
      'type' => 'wysiwyg_basic',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '6',
      'editable' => '1',
    ),
    14 => 
    array (
      'id' => '14',
      'name' => 'sort',
      'description' => '排序',
      'model' => '2',
      'type' => 'int',
      'length' => '8',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    46 => 
    array (
      'id' => '46',
      'name' => 'resources_ids',
      'description' => '资源配置',
      'model' => '2',
      'type' => 'linked_menu',
      'length' => '0',
      'values' => 'resources_class|title|3|100|1',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '8',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '7',
    1 => '9',
    2 => '10',
    3 => '14',
  ),
  'searchable' => 
  array (
    0 => '7',
  ),
);