<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['resources']=array (
  'id' => '3',
  'name' => 'resources',
  'description' => '资源管理',
  'perpage' => '5',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    15 => 
    array (
      'id' => '15',
      'name' => 'classid',
      'description' => '资源所属分类',
      'model' => '3',
      'type' => 'select_from_model',
      'length' => '8',
      'values' => 'resources_class|title',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    16 => 
    array (
      'id' => '16',
      'name' => 'title',
      'description' => '资源名称',
      'model' => '3',
      'type' => 'input',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    17 => 
    array (
      'id' => '17',
      'name' => 'cover',
      'description' => '资源封面图',
      'model' => '3',
      'type' => 'file',
      'length' => '255',
      'values' => 'jpg|png|jpeg|bmp',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    18 => 
    array (
      'id' => '18',
      'name' => 'intro',
      'description' => '资源简介',
      'model' => '3',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    19 => 
    array (
      'id' => '19',
      'name' => 'info',
      'description' => '资源详细介绍',
      'model' => '3',
      'type' => 'wysiwyg_basic',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '5',
      'editable' => '1',
    ),
    22 => 
    array (
      'id' => '22',
      'name' => 'sort',
      'description' => '排序',
      'model' => '3',
      'type' => 'int',
      'length' => '8',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    55 => 
    array (
      'id' => '55',
      'name' => 'static',
      'description' => '状态',
      'model' => '3',
      'type' => 'select',
      'length' => '8',
      'values' => 
      array (
        0 => '敬请期待',
        1 => '现已结束',
        2 => '火热进行中',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    43 => 
    array (
      'id' => '43',
      'name' => 'companies_id',
      'description' => '所属公司名称',
      'model' => '3',
      'type' => 'content',
      'length' => '8',
      'values' => 'companies|title',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '8',
      'editable' => '1',
    ),
    44 => 
    array (
      'id' => '44',
      'name' => 'products_ids',
      'description' => '配置产品',
      'model' => '3',
      'type' => 'linked_menu',
      'length' => '0',
      'values' => 'products_class|title|2|100|1',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '9',
      'editable' => '1',
    ),
    45 => 
    array (
      'id' => '45',
      'name' => 'projects_ids',
      'description' => '配置项目',
      'model' => '3',
      'type' => 'linked_menu',
      'length' => '0',
      'values' => 'projects_class|title|2|100|1',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '10',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '15',
    1 => '16',
    2 => '17',
    3 => '18',
    4 => '22',
    5 => '55',
  ),
  'searchable' => 
  array (
  ),
);