<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['category']['resources_class']=array (
  42 => 
  array (
    'classid' => '42',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'title' => 'X',
    'counts' => '0',
    'intro' => '',
    'intro_title' => '',
    'children' => '3',
    'deep' => 0,
  ),
  45 => 
  array (
    'classid' => '45',
    'parentid' => '42',
    'level' => '2',
    'path' => '{0},{42}',
    'title' => 'X分类一',
    'counts' => '10',
    'intro' => 'X分类一分类描述',
    'intro_title' => 'X分类一描述的标题',
    'children' => '0',
    'deep' => 1,
  ),
  51 => 
  array (
    'classid' => '51',
    'parentid' => '42',
    'level' => '2',
    'path' => '{0},{42}',
    'title' => 'X分类二',
    'counts' => '5',
    'intro' => 'X分类二分类描述',
    'intro_title' => 'X分类二描述标题',
    'children' => '0',
    'deep' => 1,
  ),
  54 => 
  array (
    'classid' => '54',
    'parentid' => '42',
    'level' => '2',
    'path' => '{0},{42}',
    'title' => 'X分类三',
    'counts' => '19',
    'intro' => 'X分类三分类描述',
    'intro_title' => 'X分类三描述的标题',
    'children' => '0',
    'deep' => 1,
  ),
  43 => 
  array (
    'classid' => '43',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'title' => '2',
    'counts' => '0',
    'intro' => '',
    'intro_title' => '',
    'children' => '2',
    'deep' => 0,
  ),
  58 => 
  array (
    'classid' => '58',
    'parentid' => '43',
    'level' => '2',
    'path' => '{0},{43}',
    'title' => '2分类一',
    'counts' => '0',
    'intro' => '2分类一分类描述',
    'intro_title' => '2分类一描述的标题',
    'children' => '0',
    'deep' => 1,
  ),
  62 => 
  array (
    'classid' => '62',
    'parentid' => '43',
    'level' => '2',
    'path' => '{0},{43}',
    'title' => '2分类二',
    'counts' => '230',
    'intro' => '2分类二分类描述',
    'intro_title' => '2分类二描述的标题',
    'children' => '0',
    'deep' => 1,
  ),
  44 => 
  array (
    'classid' => '44',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'title' => 'Y',
    'counts' => '0',
    'intro' => '',
    'intro_title' => '',
    'children' => '2',
    'deep' => 0,
  ),
  65 => 
  array (
    'classid' => '65',
    'parentid' => '44',
    'level' => '2',
    'path' => '{0},{44}',
    'title' => 'Y分类一',
    'counts' => '1',
    'intro' => 'Y分类一分类描述',
    'intro_title' => 'Y分类一描述的标题',
    'children' => '0',
    'deep' => 1,
  ),
  67 => 
  array (
    'classid' => '67',
    'parentid' => '44',
    'level' => '2',
    'path' => '{0},{44}',
    'title' => 'Y分类二',
    'counts' => '0',
    'intro' => 'Y分类二分类描述',
    'intro_title' => 'Y分类二描述的标题',
    'children' => '0',
    'deep' => 1,
  ),
);