<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['category']['menu']=array (
  1 => 
  array (
    'classid' => '1',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '书画动态',
    'sort' => '2',
    'url' => '',
    'menu_link' => 'home/',
    'children' => '0',
    'deep' => 0,
  ),
  4 => 
  array (
    'classid' => '4',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '书画评论',
    'sort' => '3',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 0,
  ),
  5 => 
  array (
    'classid' => '5',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '首页',
    'sort' => '1',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 0,
  ),
  6 => 
  array (
    'classid' => '6',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '排行榜',
    'sort' => '4',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 0,
  ),
  7 => 
  array (
    'classid' => '7',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '艺术展览馆',
    'sort' => '5',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 0,
  ),
  8 => 
  array (
    'classid' => '8',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '艺术拍卖行',
    'sort' => '6',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 0,
  ),
  9 => 
  array (
    'classid' => '9',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '书画知识',
    'sort' => '7',
    'url' => '',
    'menu_link' => '/home',
    'children' => '5',
    'deep' => 0,
  ),
  11 => 
  array (
    'classid' => '11',
    'parentid' => '9',
    'level' => '2',
    'path' => '{0},{9}',
    'menu_name' => '基本知识',
    'sort' => '5',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 1,
  ),
  12 => 
  array (
    'classid' => '12',
    'parentid' => '9',
    'level' => '2',
    'path' => '{0},{9}',
    'menu_name' => '历代名家',
    'sort' => '1',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 1,
  ),
  13 => 
  array (
    'classid' => '13',
    'parentid' => '9',
    'level' => '2',
    'path' => '{0},{9}',
    'menu_name' => '文人轶事',
    'sort' => '3',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 1,
  ),
  14 => 
  array (
    'classid' => '14',
    'parentid' => '9',
    'level' => '2',
    'path' => '{0},{9}',
    'menu_name' => '藏品故事',
    'sort' => '4',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 1,
  ),
  15 => 
  array (
    'classid' => '15',
    'parentid' => '9',
    'level' => '2',
    'path' => '{0},{9}',
    'menu_name' => '成名故事',
    'sort' => '2',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 1,
  ),
  10 => 
  array (
    'classid' => '10',
    'parentid' => '0',
    'level' => '1',
    'path' => '{0}',
    'menu_name' => '联系我们',
    'sort' => '8',
    'url' => '',
    'menu_link' => '/home',
    'children' => '0',
    'deep' => 0,
  ),
);